AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Service storage template
Parameters:
  RegionParameter:
    Type: String
    Description: "AWS region where the stack is deployed"
  VPC:
    Description: Name of an existing Subnets
    Type: String
    Default: 10.10.0.0/16
  Subnet1:
    Description: Name of an existing Subnets
    Type: String
    Default: 10.10.1.0/24

  Subnet2:
    Description: Name of an existing Subnets
    Type: String
    Default: 10.10.2.0/24

  Subnet3:
    Description: Name of an existing Subnets
    Type: String
    Default: 10.10.3.0/24
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: String
    Default: prod_key
    AllowedValues:
        - prod_key
        - dev_key
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t3.nano
    AllowedValues:
      - t3.nano
      - t3.small
    ConstraintDescription: must be a valid EC2 instance type.
Mappings:
  AWSInstanceType2Arch:
    t3.nano:
      Arch: HVM64
    t3.small:
      Arch: HVM64
  AWSRegionArch2AMI:
    ca-central-1:
      HVM64: ami-0ed90a3b5bde5e371
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: !Ref VPC
      Tags:
        - Key: Env
          Value: Dev
        - Key: Name
          Value: cloudx
 
  SubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref Subnet1
      VpcId: !Ref MyVPC
      AvailabilityZone: "ca-central-1a"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Env
          Value: Dev
        - Key: Name
          Value: public_a

  SubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref Subnet2
      VpcId: !Ref MyVPC
      AvailabilityZone: "ca-central-1b"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Env
          Value: Dev
        - Key: Name
          Value: public_b

  SubnetThree:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref Subnet3
      VpcId: !Ref MyVPC
      AvailabilityZone: "ca-central-1d"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Env
          Value: Dev
        - Key: Name
          Value: public_c
  myRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: MyVPC
      Tags:
        - Key: Name
          Value: public_rt

  myRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: myRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: myInternetGateway

  myInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Env
          Value: Dev

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref myInternetGateway
      VpcId: !Ref MyVPC

  SubnetRouteTableAssociationOne:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref myRouteTable
      SubnetId: !Ref SubnetOne

  SubnetRouteTableAssociationTwo:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref myRouteTable
      SubnetId: !Ref SubnetTwo

  SubnetRouteTableAssociationThree:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref myRouteTable
      SubnetId: !Ref SubnetThree
  BastionSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref MyVPC
      GroupDescription: allows access to bastion
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: bastion
  EC2poolSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref MyVPC
      GroupDescription: allows access to ec2 instances
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          SourceSecurityGroupId: !Ref BastionSecurityGroup
        - IpProtocol: tcp
          FromPort: '2049'
          ToPort: '2049'
          CidrIp: !Ref VPC
        - IpProtocol: tcp
          FromPort: '2368'
          ToPort: '2368'
          SourceSecurityGroupId: !Ref ALBSecurityGroup
      Tags:
        - Key: Name
          Value: ec2_pool
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for SSH access
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Adjust the CIDR block as per your requirements, for example, your IP range
      Tags:
        - Key: Name
          Value: SSHSecurityGroup
  ALBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref MyVPC
      GroupDescription: allows access to alb
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: alb
  EFSSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref MyVPC
      GroupDescription: defines access to efs mount points
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '2049'
          ToPort: '2049'
          SourceSecurityGroupId: !Ref EC2poolSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: '0'
          ToPort: '65535'
          CidrIp: !Ref VPC
      Tags:
        - Key: Name
          Value: efs
  MyKeyName:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: ghost-ec2-pool
  GhostRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: ghost_app_policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
  GhostInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName: ghost_app
      Path: /
      Roles:
        - !Ref GhostRole

  FileSystemResource:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      BackupPolicy:
        Status: ENABLED
      PerformanceMode: generalPurpose
      Encrypted: false
      LifecyclePolicies:
        - TransitionToIA: AFTER_7_DAYS
      FileSystemTags:
        - Key: Name
          Value: ghost_content
      FileSystemPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "elasticfilesystem:ClientRootAccess"
              - "elasticfilesystem:ClientMount"
              - "elasticfilesystem:ClientWrite"
            Principal: '*'
  MountTargetResource1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystemResource
      SubnetId:
        Ref: SubnetOne
      SecurityGroups:
        - !GetAtt MyVPC.DefaultSecurityGroup
        - !Ref EFSSecurityGroup

  MountTargetResource2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystemResource
      SubnetId:
        Ref: SubnetTwo
      SecurityGroups:
        - !GetAtt MyVPC.DefaultSecurityGroup
        - !Ref EFSSecurityGroup

  MountTargetResource3:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystemResource
      SubnetId:
        Ref: SubnetThree
      SecurityGroups:
        - !GetAtt MyVPC.DefaultSecurityGroup
        - !Ref EFSSecurityGroup
#
  MyGhostALB:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
        Name: my-alb
        Scheme: internet-facing
        Subnets:
          - !Ref SubnetOne
          - !Ref SubnetTwo
          - !Ref SubnetThree
        SecurityGroups:
          - !Ref ALBSecurityGroup

  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: ghost-ec2
      Port: 2368
      Protocol: HTTP
      VpcId: !Ref MyVPC
      HealthCheckProtocol: HTTP
      HealthCheckPort: 80
      HealthCheckPath: /
      TargetType: instance
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '60'

  MyListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup
      LoadBalancerArn: !Ref MyGhostALB
      Port: 80
      Protocol: HTTP

  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: ghost
      LaunchTemplateData:
        ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', !FindInMap [AWSInstanceType2Arch, !Ref InstanceType, Arch]]
        InstanceType: t3.small           # Replace with your desired instance type
        KeyName: !Ref MyKeyName
        SecurityGroupIds:
          - !Ref EC2poolSecurityGroup
        IamInstanceProfile:
          Arn: !GetAtt GhostInstanceProfile.Arn
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe
            exec > >(tee /var/log/cloud-init-output.log|logger -t user-data -s 2>/dev/console) 2>&1
            
            REGION=${RegionParameter}
            EFS_ID=$(aws efs describe-file-systems --query 'FileSystems[0].FileSystemId' --output text)
            LB_DNS_NAME=$(aws elbv2 describe-load-balancers --query 'LoadBalancers[0].DNSName' --output text)
            
            ### Install pre-reqs
            curl -sL https://rpm.nodesource.com/setup_18.x | sudo bash -
            yum install -y nodejs amazon-efs-utils
            npm install ghost-cli@latest -g
            
            adduser ghost_user
            usermod -aG wheel ghost_user
            cd /home/ghost_user/
            
            sudo -u ghost_user ghost install [5.80.1] local
            
            ### EFS mount
            mkdir -p /home/ghost_user/content/data
            mount -t efs -o tls $EFS_ID:/ /home/ghost_user/content
            
            cat << EOF > config.development.json
            
            {
              "url": "http://$LB_DNS_NAME",
              "server": {
                "port": 2368,
                "host": "0.0.0.0"
              },
              "database": {
                "client": "sqlite3",
                "connection": {
                  "filename": "/home/ghost_user/content/data/ghost-local.db"
                }
              },
              "mail": {
                "transport": "Direct"
              },
              "logging": {
                "transports": [
                  "file",
                  "stdout"
                ]
              },
              "process": "local",
              "paths": {
                "contentPath": "/home/ghost_user/content"
              }
            }
            EOF
            
            sudo -u ghost_user ghost stop
            sudo -u ghost_user ghost start
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: MyEC2Instance

  MyAutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate
        Version: '1'
      VPCZoneIdentifier:
        - !Ref SubnetOne
        - !Ref SubnetTwo
        - !Ref SubnetThree
      TargetGroupARNs:
        - !Ref MyTargetGroup
      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '1'
      AvailabilityZones: !GetAZs ''
      Tags:
        - Key: 'Name'
          Value: 'ghost_ec2_pool'
          PropagateAtLaunch: 'true'

  MyBastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', !FindInMap [AWSInstanceType2Arch, !Ref InstanceType, Arch]]
      InstanceType: t3.nano  # Specify the instance type (e.g., t3.nano, t3.small, etc.)
      KeyName: dev_key
      SecurityGroupIds:
        - !Ref BastionSecurityGroup
      SubnetId: !Ref SubnetOne
      Tags:
        - Key: 'Name'
          Value: 'BastionHost'
Outputs:
  ALBDNSName:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt MyGhostALB.DNSName
