AWSTemplateFormatVersion: 2010-09-09
Parameters:
  VPC:
    Description: Name of an existing Subnets
    Type: String
    Default: 172.33.0.0/16
  Subnet1:
    Description: Name of an existing Subnets
    Type: String
    Default: 172.33.0.0/24

  Subnet2:
    Description: Name of an existing Subnets
    Type: String
    Default: 172.33.16.0/24

  Subnet3:
    Description: Name of an existing Subnets
    Type: String
    Default: 172.33.32.0/24

Resources:
  MountTargetVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPC
      Tags:
        - Key: Env
          Value: Dev
        - Key: Name
          Value: MyVPC
 
  MountTargetSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref Subnet1
      VpcId: !Ref MountTargetVPC
      AvailabilityZone: "ca-central-1a"
      Tags:
        - Key: Env
          Value: Dev
        - Key: Name
          Value: MySubnet

  MountTargetSubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref Subnet2
      VpcId: !Ref MountTargetVPC
      AvailabilityZone: "ca-central-1b"
      Tags:
        - Key: Env
          Value: Dev
        - Key: Name
          Value: MySubnet

  MountTargetSubnetThree:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref Subnet3
      VpcId: !Ref MountTargetVPC
      AvailabilityZone: "ca-central-1d"
      Tags:
        - Key: Env
          Value: Dev
        - Key: Name
          Value: MySubnet

  myRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: MountTargetVPC
      Tags:
        - Key: Env
          Value: Dev
        - Key: Name
          Value: MyRouteTable